apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dep-cart
    path: patch-1-deployment.yaml

  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: rt-cart
    path: patch-3-route.yaml
